export default {
  generic: {
    intro: { hospitality: `"Hi [Name], this is [SDR] from Ottimate. I work with CFOs at similar-sized hospitality operations, and in this economy, I'm curious: how are you handling accounts payable to ensure it's not a cost sink?"`, grocery: `"Hi [Name], this is [SDR] from Ottimate. I work with CFOs at similar-sized grocery operations, and in this economy, I'm curious: how are you handling accounts payable to ensure it's not a cost sink?"`, healthcare: `"Hi [Name], this is [SDR] from Ottimate. I work with CFOs at similar-sized healthcare operations, and in this economy, I'm curious: how are you handling accounts payable to ensure it's not a cost sink?"` },
    discovery: ["What's your current AP cycle time, invoice in to payment out?", "Do you have visibility into duplicate invoices, vendor overcharges, or early pay discounts you're missing?", "If I told you there was typically $100K-$500K sitting in your AP process that you're not seeing, would that be material?"],
    listenFor: "Listen for cost, margin, and cash flow language. CFOs buy on financial impact, not time savings.",
    hook: { hospitality: `"Based on what I see with hospitality operators at your scale, there's typically $143K a month in duplicate invoices that slip through approval. That's $1.7M a year in leakage."`, grocery: `"Grocers typically don't catch 5% overcharges on invoices. That's not human error, that's vendor behavior. One of our customers found $4.9M in cost discrepancies in year one."`, healthcare: `"Healthcare organizations lose an average of $136K a month to duplicate invoices alone."` },
    pitch: { hospitality: ["A 50-property restaurant group caught $143K a month in duplicates. Their cash position improved by $1.2M in the first 90 days."], grocery: ["A 115-store grocer caught $4.9M in cost discrepancies in year one. Not just time savings: cost recovery."], healthcare: ["A 103-site dental DSO caught $136K+ a month in duplicates and improved cash position by $800K in 90 days."] },
    close: `"Would it make sense to spend 20 minutes with our team to model the cost recovery for your specific operation?"`,
  },
  vendor_friction: {
    intro: { hospitality: `"Hi [Name], this is [SDR] from Ottimate. In the current economy, tracking any possible money leakage is critical. Where in your AP process is money leaking that you haven't addressed yet?"`, grocery: `"Hi [Name], this is [SDR] from Ottimate. In the current economy, tracking any possible money leakage is critical. Where in your AP process is money leaking that you haven't addressed yet?"`, healthcare: `"Hi [Name], this is [SDR] from Ottimate. In the current economy, tracking any possible money leakage is critical. Where in your AP process is money leaking that you haven't addressed yet?"` },
    discovery: ["In AP specifically, what would a 2-3% improvement in cost spend look like to your P&L?", "Are you currently getting any vendor discounts, or is that a blind spot?", "Have you had any AP-related write-offs, adjustments, or audit findings in the last 12 months?"],
    listenFor: `"Margin pressure," "cost leaks," "vendor issues," "duplicate payments," "missed discounts"`,
    hook: { hospitality: `"A 50-property group found $1.7M a year in duplicate invoices they were missing. That went straight to the bottom line."`, grocery: `"A grocer caught $4.9M in vendor overcharges. That's not new revenue. That's pure margin recovery."`, healthcare: `"A DSO recovered $136K a month in duplicates. The highest-margin initiative they've had all year."` },
    pitch: { hospitality: ["B&G Food went from missing $143K a month to catching nearly every duplicate. That's $1.7M a year to your EBITDA."], grocery: ["Heritage Grocers, 115 stores, now processes AP in a quarter of the time AND catches cost errors."], healthcare: ["Gen4 Dental cut AP processing time by 80% while improving cost accuracy. EBITDA improvement was their focus."] },
    close: `"Would it make sense to spend 20 minutes showing you the cost recovery model? We can use your own invoice volume."`,
  },
};
