export default {
  generic: {
    intro: { hospitality: `"Hi [Name], this is [SDR] from Ottimate. We work with a lot of hospitality controllers, and I had a quick question: do you ever come in on Monday morning and find that half your invoices still aren't coded?"`, grocery: `"Hi [Name], this is [SDR] from Ottimate. We work with a lot of grocery controllers, and I had a quick question: do you ever come in on Monday morning and find that half your invoices still aren't coded?"`, healthcare: `"Hi [Name], this is [SDR] from Ottimate. We work with a lot of healthcare controllers, and I had a quick question: do you ever come in on Monday morning and find that half your invoices still aren't coded?"` },
    discovery: ["Walk me through what happens when an invoice comes in today. What does that workflow look like?", "How many hours is your team spending on month-end close right now?", "In an ideal world, what would you prefer to have your team working on that would really move the lever for the business?", "What's the one thing about your AP process that keeps you up at night?"],
    listenFor: "Listen for trigger signals, then pivot to the appropriate trigger script.",
    hook: { hospitality: `"Based on what I see with hospitality operators at your scale, there's typically $143K a month in duplicate invoices and $1.7M a year in total duplicate exposure that nobody catches."`, grocery: `"Based on my research, grocers your size are unknowingly overcharged about 5% on invoices. One of our customers found $4.9 million in cost discrepancies in their first year alone."`, healthcare: `"Our healthcare customers catch an average of $136K per month in duplicate invoices and save $1.2M a year in invoice lifecycle management."` },
    pitch: { hospitality: ["B&G Food cut their weekly AP workload by 90%, from 50 hours down to 4.", "NorthStone Country Club has 90% of their invoices automatically coded.", "Your cost centers, approval chains, and property-level visibility are all native to the platform."], grocery: ["Estevez Markets runs invoice digitization in about 1 hour a day across 10 locations.", "Heritage Grocers Group reduced processing time by 70% across 115 stores.", "We handle direct store delivery workflows, cost file validation, and receiver matching."], healthcare: ["Gen4 Dental, a 103-site DSO, handles 6,000+ invoices a month with a lean team.", "West Harbor Healthcare cut AP time by 80%.", "We're the only AP platform with automatic PHI Redaction, HIPAA-compliant storage, and an Invoice Trust Score."] },
    close: `"Would it make sense to spend 20 minutes with someone on our team who can show you what this looks like for a [vertical] operation like yours?"`,
  },
  staff_turnover: {
    intro: { hospitality: `"Hi [Name], this is [SDR] from Ottimate. I noticed [company] is hiring for an AP role. I know how tough that is right now. How is the team handling the workload while that position is open?"`, grocery: `"Hi [Name], this is [SDR] from Ottimate. I noticed [company] is hiring for an AP role. I know how tough that is right now. How is the team handling the workload while that position is open?"`, healthcare: `"Hi [Name], this is [SDR] from Ottimate. I noticed [company] is hiring for an AP role. I know how tough that is right now. How is the team handling the workload while that position is open?"` },
    discovery: ["Have you had any turnover on your AP team in the last 12 months? What happened to the workload when that person left?", "How long has the position been open? How are you covering it?", "How long does it take to train a new AP person on your coding and approval process?", "What made you start thinking about this now, as opposed to six months ago?"],
    listenFor: `"Hired," "open position," "turnover," "we can't find," "can't keep up," "stretched"`,
    hook: { hospitality: `"What I'm hearing from a lot of controllers right now is that the staffing problem isn't going away. Our hospitality customers identify $143K per month in duplicate invoices. When you're short-staffed, those slip through even faster."`, grocery: `"What I'm hearing from a lot of controllers right now is that the staffing problem isn't going away. Grocers of your size are unknowingly overcharged about 5% on invoices. With a lean team, nobody has time to check."`, healthcare: `"What I'm hearing from a lot of controllers right now is that the staffing problem isn't going away. Healthcare organizations lose an average of $136K per month in duplicate invoices, and with a 7% duplicate rate, that exposure grows fast when you're understaffed."` },
    pitch: { hospitality: ["B&G Food cut their weekly AP workload by 90%, from about 50 hours a week down to 4.", "NorthStone Country Club has 90% of their invoices automatically coded.", "Your team gets to dig out of the busy work and focus on what moves the needle."], grocery: ["Estevez Markets got their AP workload down to about 1 hour a day across 10 locations.", "Heritage Grocers Group reduced processing time by 70% across 115 stores.", "We handle DSD workflows, cost file validation, and receiver matching, so your lean team doesn't have to manually check every invoice."], healthcare: ["Gen4 Dental, a 103-site DSO, handles 6,000+ invoices a month with a lean team, no new hires.", "West Harbor Healthcare cut AP time by 80%.", "You can continue to scale without increasing the lift on your already taxed team."] },
    close: `"Would it make sense to spend 20 minutes with someone on our team who can show you exactly how [proof point customer] did this, and what it would look like for [their company]?"`,
  },
  month_close: {
    intro: { hospitality: `"Hi [Name], this is [SDR] from Ottimate. I work with a lot of hospitality controllers, and this time of month I hear the same thing: month-end close is eating people alive. Is that something you're dealing with right now?"`, grocery: `"Hi [Name], this is [SDR] from Ottimate. I work with a lot of grocery controllers, and this time of month I hear the same thing: month-end close is eating people alive. Is that something you're dealing with right now?"`, healthcare: `"Hi [Name], this is [SDR] from Ottimate. I work with a lot of healthcare controllers, and this time of month I hear the same thing: month-end close is eating people alive. Is that something you're dealing with right now?"` },
    discovery: ["Walk me through the last 48 hours of your most recent month-end close. How many people were involved, and how many of those hours were overtime?", "What's the biggest bottleneck that slows the close down: coding, approvals, or chasing missing invoices?", "If you could wave a magic wand and fix one thing about your current month-end close process, what would it be?"],
    listenFor: `"Nightmare," "worked the weekend," "it's a mess," "we're always late"`,
    hook: { hospitality: `"Do you ever find yourself working weekends just to close the books? The Club at Admirals Cove was in that exact spot. Their invoices took about 24 hours to process. After Ottimate, that dropped to under 5 minutes."`, grocery: `"Our grocery customers save an average of 450 hours a year on AP. Heritage Grocers Group, running 115 stores, cut processing time by 70%."`, healthcare: `"Gen4 Dental shaved a full day off their month-end AP close across 103 sites. Internal questions that took 1 to 2 days to resolve now take minutes."` },
    pitch: { hospitality: ["Lazy Bear went from 12-15 hours a week on AP down to about 2 hours.", "The Club at Ravenna saw an 80% reduction in invoice processing time."], grocery: ["Estevez Markets processes AP in about 1 hour a day across 10 locations.", "We handle DSD workflows, cost file validation, and receiver matching during end-of-month close."], healthcare: ["Gen4 processes an invoice from beginning to end, including payment proof, in a few hours instead of days."] },
    close: `"Would it make sense to spend 20 minutes looking at how we could take a day or two off your close? Our team can model it based on your actual volume."`,
  },
  audit: {
    intro: { hospitality: `"Hi [Name], this is [SDR] from Ottimate. I work with a lot of hospitality controllers who've been dealing with audit findings around AP documentation. It's more common than you'd think. Has that come up for your team recently?"`, grocery: `"Hi [Name], this is [SDR] from Ottimate. I work with a lot of grocery controllers who've been dealing with audit findings around AP documentation. Has that come up for your team recently?"`, healthcare: `"Hi [Name], this is [SDR] from Ottimate. I work with a lot of healthcare controllers who've been dealing with audit findings around AP documentation. Has that come up for your team recently?"` },
    discovery: ["When was your last audit? Did anything come back around AP documentation or approval controls?", "Is there a high-level mandate to fix this, or is it more of a 'we should get to this' situation?", "If an auditor asked you to pull every invoice and approval record for a vendor over the last 18 months, how long would that take?"],
    listenFor: `"Auditors flagged," "board is asking," "got written up," "compliance deadline," "HIPAA concern"`,
    hook: { hospitality: `"Our hospitality customers maintain complete audit trails automatically. Every invoice, every approval, every GL code change is tracked and reportable in seconds, not days."`, grocery: `"Grocers are under increasing margin pressure, and auditors are paying closer attention to AP controls. Our Cost File Validation catches line-level discrepancies that manual processes miss."`, healthcare: `"Invoices with PHI expose you to HIPAA violations with fines up to $2M a year. Ottimate is the only AP platform with automatic PHI Redaction, audit controls, and invoice trust scoring."` },
    pitch: { hospitality: ["A hospitality operator with 50 locations went from 'we can't find that approval' to 'we can pull the audit trail in 30 seconds.'"], grocery: ["A 115-store grocery group eliminated 'we don't know why that was coded that way' in their audits."], healthcare: ["A DSO with PHI across 1,000+ invoices monthly now has automated redaction and HIPAA compliance built in. Zero audit findings on AP controls."] },
    close: `"Would it make sense to spend 20 minutes showing you exactly how we build this into the platform, so you can close out these audit findings permanently?"`,
  },
};
